### PR TITLE
Added sound, as well as the code to run it. Fix #2

### LINKED ISSUE #2: Sound notifications
Notifying the clients when a new message pops up.

### PR DESCRIPTION
**Pull request by dat-adi**
Used *pygame* in order to play the notification sound.
Might need to consider adding *pygame* as a pre-requisite, if you wish to approve this pull request for the fix.

If you need to change the sound due to any issue, just change the name of the sound file after adding the sound to the assets.

### CODE REVIEW

**Comment by dat-adi** [comment]
#3 Fixes #2

**Comment by 1StranGe** [comment]
The changes are good. However, the notification sounds play even when the client sends a message. i.e., every time the server broadcasts a message to the clients the user is notified. 
It would be better if the client was notified **only** when receiving a message from a different user.

**Comment by dat-adi** [comment]
Yeah, noted and done.

**Comment by 1StranGe** [comment]
The changes seem good. 
However, after a bit of googling, I figured that you can create a sound by using `print("\a")`.
It's a better alternative to downloading an entire module and loading an audio file.
Consider the changes, and I will merge the pull request.

**Pull request merged**
